### ISSUE TITLE
Compare hashing speed to c++ speeds

### ISSUE THREAD

**Issue by BrandonT42** [turtlecoin/cs-turtlecoin#31]
The c# hashing speeds are slower than the c++ implementation, and I think this may be a limitation of the language. I'd like to import methods from the [standalone crypto library](https://github.com/turtlecoin/turtlecoin-crypto) and see if the speeds are better.

**Comment by zpalmtree** [comment]
I think the main issue in speed is due to not having AES intrinsics. There is https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.aes?view=netcore-3.0 but it's very new.

**Comment by BrandonT42** [comment]
I want to try importing the crypto library, which would be compiled in c++ and try speed testing it again... I'm not 100% sure, but I *feel* like it should be faster, since the code running wouldn't be reliant on netcore, right?

**Comment by zpalmtree** [comment]
Sure, it'll probably be the best way to do it, and the fastest, just putting it out there that I don't think it's primarily a language limitation (I would expect maybe 2x slowdown with fully optimized code)

**Comment by BrandonT42** [comment]
Gotcha 😄

**Comment by BrandonT42** [comment]
Benchmarking proves this as the case, moving forward with using TurtleCoin-Crypto as the cryptography backend, will be keeping C# implementations tucked away somewhere safe *just in case* :D

**Comment by zpalmtree** [comment]
Not so fast!

![image](https://user-images.githubusercontent.com/22151537/58725211-7de65d80-83d6-11e9-9745-2d69cd4c01c3.png)
Left: cs-turtlecoin
Right: C++ cryptotest

**Comment by brandonlehmann** [comment]
> Not so fast!
> 
> ![image](https://user-images.githubusercontent.com/22151537/58725211-7de65d80-83d6-11e9-9745-2d69cd4c01c3.png)
> Left: cs-turtlecoin
> Right: C++ cryptotest

lies

**Comment by zpalmtree** [comment]
PR soon :)

**Comment by BrandonT42** [comment]
Look what you did, now I'm gonna have to benchmark each hashing algorithm and pick and choose whether to use the CS or C++ implementation 😛

**Comment by zpalmtree** [comment]
I only optimized slow hash so far, but I would much prefer for us to use native C# where possible - cross platform, easier to read, don't need a C++ compiler, etc - So if there's a specific hashing algorithm where you think it *needs* to be faster, then I can try and optimize specific ones.

Right now I think fast hash is signficantly slower, so I'll look at that next after I'm done with this - but other than slow and fast hash, are there any primitives which we really need to be super fast, other than wallet syncing primitives?

(Not sure if you're actually targetting making a wallet in the C# code, doesn't particuarly seem needed to me at least not at the beginning)

**Comment by RocksteadyTC** [comment]
not sure we have a policy on photoshops, but ill review the bylaws in the meantime

**Comment by BrandonT42** [comment]
Other than `tree_hash`, nothing is coming to mind off the top of my head, although `tree_hash` seems to be more or less reliant on `cn_fast_hash` for its own operations. I'll have to let you know once I dig into the code a bit more.

P.S., nice job 😀

**Comment by zpalmtree** [comment]
Think this can be closed now.
